name: Litigence
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.1.0+6

environment:
  sdk: '>=3.2.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. 
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.4
  html: ^0.15.4
  http: ^1.2.0
  chat_bubbles: ^1.5.0
  flutter_markdown: ^0.7.3+2
  dots_indicator: ^3.0.0
  cool_alert: ^2.0.1
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  go_router: ^14.3.0
  # flutter_dotenv: ^5.1.0
  chatview: ^2.2.0
  firebase_crashlytics: any
  flutter_firebase_chat_core: any
  pinput: ^5.0.0
  easy_container: ^1.0.5
  intl_phone_field: ^3.2.0
  firebase_phone_auth_handler: any

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0 # Corrected syntax and added a valid version

# For information on the generic Dart part of this file, see:
# https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/
    - assets/onboard/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
